### ISSUE TITLE
Installation instructions incorrect

### ISSUE THREAD

**Issue by dvincelli** [kevinjqiu/spectrum.vim#6]
Hi Kevin,

I think you copied the install instructions from vundle cause your docs say to clone vundle's git dir and then copy the plugin directory over to your $HOME/.vim folder.
- David

**Comment by kevinjqiu** [comment]
You're right. I copied the vundle git url rather than spectrum's. It should be simply clone the spectrum repo and copy \* to .vim/
I'll fix it. Thanks for pointing it out.
